### PR TITLE
Add English Language

### PR DESCRIPTION
**Pull request by ithinkido**
Converted for English language and layout as per https://simongolms.github.io/QLOCKGENERATOR/#/home EN
I have only done the basic conversion. I think this would be great to add this as a menu item for example in the "General Configuration - Clock Type" to be able to chose between French / English ( and maybe other languages in the future ) This is something I am not able to do, so if you would like to take a look and for adding it in the menu , that would be great

### CODE REVIEW

**Comment by psykokwak-com** [comment]
Let me check in few days.

**Comment by psykokwak-com** [comment]
Check the latest latest commit :)

**Comment by ithinkido** [comment]
> Check the latest latest commit :)

That looks perfect !!  I think that this will make it very usable for many people . Everyone can add their own language / dialect. SUPER !!!

**Comment by psykokwak-com** [comment]
> That looks perfect !! I think that this will make it very usable for many people . Everyone can add their own language / dialect. SUPER !!!

If you add new languages, do not forget the pull request. I will add them.

**Pull request closed without merging**
